# This is a basic workflow to help you get started with Actions

name: 'check cv and receive QR code'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  schedule:
    - cron: '21 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: check and receive
      run: python3 main.py --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --From ${{ secrets.NAME }}
